# Generated by Django 4.2.13 on 2024-06-30 04:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('productID', models.AutoField(default='undisclosed', primary_key=True, serialize=False)),
                ('productname', models.CharField(max_length=255)),
                ('productNumber', models.IntegerField()),
                ('price', models.FloatField()),
                ('production_date', models.DateField(max_length=255)),
                ('expiry_date', models.DateField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyername', models.CharField(max_length=255)),
                ('units', models.IntegerField()),
                ('location', models.CharField(max_length=255)),
                ('productID', models.ForeignKey(default='undisclosed', null=True, on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
        ),
    ]
